fieldLayouts:
  c4ffb56d-84a5-4a53-9896-7bdb83db105f:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 754f7c9c-9628-445e-b7ae-a0507027dcda
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: aboutUs
hasTitleField: true
name: 'About Us'
section: 47d75f95-df65-48ac-ad7c-041e179c2f91
sortOrder: 1
titleFormat: Title
titleTranslationKeyFormat: null
titleTranslationMethod: site
