fieldLayouts:
  785fd4c0-581c-40d5-ba41-e638ab0e08f7:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 05667574-50ca-4551-8b7e-280fa7e7de09
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 754f7c9c-9628-445e-b7ae-a0507027dcda
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: search
hasTitleField: true
name: Search
section: 6cf6d065-a0a7-42ef-be17-1cab9a2b297f
sortOrder: 1
titleFormat: title
titleTranslationKeyFormat: null
titleTranslationMethod: site
