enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  a00bf94e-219f-4bdf-b1c0-6243a67d730d:
    enabledByDefault: true
    hasUrls: true
    template: home
    uriFormat: __home__
type: single
